// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	Createusers(ctx context.Context, arg CreateusersParams) (Users, error)
	Deleteusers(ctx context.Context, id int64) error
	Getusers(ctx context.Context, id int64) (Users, error)
	GetusersForUpdate(ctx context.Context, id int64) (Users, error)
	Listusers(ctx context.Context, arg ListusersParams) ([]Users, error)
	Updateusers(ctx context.Context, arg UpdateusersParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
